### PR TITLE
Add overlay alpha test

### PR DESCRIPTION
**Pull request by NissimHadar**
# Description
This test was written to test the display of overlays that are `drawInFront` - this was not working when alpha was not set to 1.0.

### CODE REVIEW

**Comment by SamGondelman** [comment]
Can we move these to content/overlay/layer/drawInFront/alpha?  They're specifically testing the layering.

**Comment by SamGondelman** [comment]
That would be great!

**Comment by SamGondelman** [comment]
Looks like some other files made it in there?

**Comment by NissimHadar** [comment]
WTF .... GitHub is causing me some weird issues.

**Pull request closed without merging**
